### ISSUE TITLE
Invalid sources reference in source maps

### ISSUE THREAD

**Issue by mazswojejzony** [actimeo/ng2-i18next#2]
When ng2-i18next is installed via npm there is no `src` folder in the `node_modules/ng2-i18next` folder. Yet `sources` in e.g. `i18n-service.js.map` reference `../src/i18n-service.ts` file. As a result I get the following warnings during my webpack build:

```
WARNING in ./~/ng2-i18next/lib/i18n-service.js
Cannot find source file '../src/i18n-service.ts': Error: Cannot resolve 'file'
    or 'directory' ../src/i18n-service.ts in c:\dev\Inform\node_modules\ng2-i18next\lib
```

Shouldn't the `src` folder be included in the module package? Currently it is ignored via `.npmignore`.

**Comment by actimeo** [comment]
You are right. These map files don't have mush interest without the source files. I've added them to the npm package, in v0.0.8

**Comment by mazswojejzony** [comment]
Works perfectly now. Thanks a lot for a quick turnaround!
