### ISSUE TITLE
Consider using a different name for the `alert$` property

### ISSUE THREAD

**Issue by mazswojejzony** [actimeo/ng2-i18next#3]
Disclaimer first: feel free to reject/close this issue as this is more of a style/taste preference. ;-)

Wouldn't the `this.i18n.alerts$.subscribe` read better as `this.i18n.whenReady.subscribe` or maybe `this.i18n.whenInitiazlied.subscribe`? 

`alert$` seems strange to me. But again, maybe it is just me. :-)

**Comment by actimeo** [comment]
As a matter of fact, it's a misnamed variable. I'll change it.

**Comment by mazswojejzony** [comment]
Thanks a lot! :-)
