### ISSUE TITLE
Update to Angular RC 1

### ISSUE THREAD

**Issue by mazswojejzony** [actimeo/ng2-i18next#5]
Any short-term plans to do this?

**Comment by actimeo** [comment]
Hi,

Have you seen version 0.1.0 ? This one should be ok.

Le 16 mai 2016 13:21:25 GMT+02:00, mazswojejzony notifications@github.com a écrit :

> Any short-term plans to do this?
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/actimeo/ng2-i18next/issues/5

## 

Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by mazswojejzony** [comment]
Yes, it is OK.

BTW: why 0.1.0 is not visible on GitHub?

Thanks!

**Comment by actimeo** [comment]
Oh, I forgot to push to github. That should be ok now.
